name: Backmerge Main to Develop

on:
  push:
    branches:
      - main

jobs:
  backmerge:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch all branches
        run: git fetch --all

      - name: Get the highest release number
        id: get_release_number
        run: |
          # List all branches and filter only release branches
          RELEASE_BRANCHES=$(git branch -r | grep -oP 'release/\d+' | sed 's|release/||')
          echo "Found release branches: $RELEASE_BRANCHES"

          # Find the highest release number
          MAX_RELEASE=$(echo "$RELEASE_BRANCHES" | sort -nr | head -n 1)
          echo "Highest release number: $MAX_RELEASE"

          # Save the highest release number in an environment variable
          echo "MAX_RELEASE=$MAX_RELEASE" >> $GITHUB_ENV

      - name: Output the highest release number
        run: |
          echo "The highest release number is: ${{ env.MAX_RELEASE }}"

      - name: Create a new branch
        run: |
          git checkout -b backmerge/$MAX_RELEASE
          echo "New branch created: backmerge/$MAX_RELEASE"

      - name: Create a pull request
        env:
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
          RELEASE_NUMBER: ${{ env.MAX_RELEASE }}
        run: |
          curl --request POST \
            --url https://api.github.com/repos/${REPO_OWNER}/${REPO_NAME}/pulls \
            --header "Authorization: token ${{ secrets.SECRET_KEY }}" \
            --header "Content-Type: application/json" \
            --header "User-Agent: ${REPO_OWNER}" \
            --data '{
              "title": "Backmerge main into develop",
              "head": "backmerge/${RELEASE_NUMBER}",
              "base": "develop",
              "body": "### Checklist:\n\n- [ ] Update the `pom.xml` with a new version.\n- [ ] Add the `-SNAPSHOT` to the new version.\n\nThis PR was created automatically to synchronize changes from `main` to `develop`."
            }'
