name: Backmerge Main to Develop

on:
  push:
    branches:
      - main

jobs:
  backmerge:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch all branches
        run: git fetch --all

      - name: Create a new branch for the backmerge
        run: |
          git checkout main
          git checkout -b backmerge-main-to-develop9

      - name: Push the backmerge branch
        run: |
          git push origin backmerge-main-to-develop9
      - name: Create PR
        run: |
          curl -X POST  -H "Authorization: ${{ secrets.GITHUB_TOKEN }}" -H "Content-Type: application/json" -d '{"title": "Backmerge main into develop","head": "backmerge-main-to-develop","base": "develop","body": "Este PR foi criado automaticamente para sincronizar alterações da main na develop."}' https://api.github.com/repos/WellingtonDefassio/action-backmerge/pulls
      - name: Create a pull request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: develop
          title: "Backmerge main into develop"
          body: "This is an automated pull request to backmerge changes from main into develop."
          draft: always-true